# Generated by Django 5.1 on 2024-08-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.CharField(max_length=300)),
                ('lavozimlar', models.CharField(max_length=50)),
                ('eslatma', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
