# Generated by Django 5.1 on 2024-08-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=20)),
                ('tuman', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
