# Generated by Django 5.1 on 2024-08-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dastavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz', models.CharField(max_length=150)),
                ('fio', models.CharField(max_length=100)),
                ('maxsulot', models.CharField(max_length=150)),
                ('naqt', models.FloatField()),
                ('plastik', models.FloatField()),
                ('sana', models.DateField()),
                ('auto', models.CharField(max_length=50)),
                ('holat', models.BooleanField()),
            ],
        ),
    ]
