# Generated by Django 5.1 on 2024-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastavka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dastavka',
            name='kol_vo_voda',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
