# Generated by Django 5.1 on 2024-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontragent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontragent',
            name='manzil',
        ),
        migrations.AddField(
            model_name='kontragent',
            name='latitute',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontragent',
            name='longitute',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kontragent',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
