# Generated by Django 5.1 on 2024-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='manzil',
        ),
        migrations.AddField(
            model_name='customer',
            name='latitute',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitute',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tuman',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
