# Generated by Django 5.1 on 2024-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('fio', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('suv_miqdori', models.CharField(max_length=20)),
                ('viloyat', models.CharField(max_length=70)),
                ('tuman', models.CharField(max_length=120)),
                ('manzil', models.CharField(max_length=200)),
                ('sana_vaqt', models.DateTimeField()),
                ('dastavka', models.BooleanField()),
                ('eslatma', models.CharField(max_length=300)),
                ('auto', models.IntegerField()),
            ],
        ),
    ]
