# Generated by Django 5.1 on 2024-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sana_vaqt',
        ),
        migrations.AddField(
            model_name='order',
            name='latitute',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitute',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sana',
            field=models.DateField(default='2024-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='vaqt',
            field=models.TimeField(default='12:12'),
            preserve_default=False,
        ),
    ]
