# Generated by Django 5.1 on 2024-08-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xarita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('fio', models.CharField(max_length=150)),
                ('longitute', models.FloatField()),
                ('latitute', models.FloatField()),
            ],
        ),
    ]
