# Generated by Django 5.1 on 2024-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('pul', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=50)),
                ('asosiy_mahsulot', models.BooleanField()),
                ('eslatma', models.CharField(max_length=300)),
            ],
        ),
    ]
